# roles/prereqs/tasks/prereqs_debian.yaml
---
- name: Install debian specific prerequisite packages
  ansible.builtin.package:
    name:
      - apt-transport-https
      - ca-certificates
    state: present
