# playbook.yaml
---
- name: Setup chromebook
  hosts: localhost
  tasks:
    - name: Load vars
      ansible.builtin.include_vars: main.yaml

    - name: Load distribution vars
      ansible.builtin.include_vars: "{{ ansible_distribution | lower }}.yaml"

    - name: Install pre-requisites
      ansible.builtin.include_role:
        name: "prereqs"
        apply:
          become: true

    - name: Install common packages
      ansible.builtin.include_role:
        name: packages_common
        apply:
          become: true

    - name: Install vscode
      ansible.builtin.include_role:
        name: install_vscode
        apply:
          become: true
