#playbook.yaml
---
- hosts: localhost

  tasks:
    - name: load vars
      include_vars: main.yaml

    - name: load distribution vars
      include_vars: "{{ ansible_distribution | lower }}.yaml"

    - name: install pre-requisites
      include_role:
        name: "prereqs"
        apply:
          become: yes

    - name: install common packages
      include_role:
        name: packages-common
        apply:
          become: yes

    - name: install-vscode
      include_role:
        name: install-vscode
        apply:
          become: yes
